locale: de

backend:
  name: github
  repo: mvbuerglen/website
  branch: main

media_folder: src/assets/images

show_preview_links: false
search: false

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: seiten
    label: Seiten
    label_singular: Seite
    identifier_field: title
    folder: src/pages
    create: false
    delete: false
    extension: md
    format: yaml-frontmatter
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Titel
        name: title
        widget: hidden
      - label: Layout
        name: layout
        widget: hidden
      - label: Bilder
        name: bild
        required: false
        widget: "list"
        max: 10
        min: 0
        collapsed: false
        field:
          name: bild
          widget: image
          label_singular: Bild
          required: true
          allow_multiple: false
          choose_url: false
          media_library:
            config:
              max_file_size: 1048576 # 1MB
      - label: Inhalt
        name: body
        widget: markdown
  - name: anlaesse
    label: Anlässe
    label_singular: Anlass
    folder: src/content/anlaesse
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Titel
        name: title
        widget: string
        hint: z.B. Winterkonzert
      - label: Datum
        name: datum
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ssZZ"
        picker_utc: false
        hint: Datum und lokale Uhrzeit
      - label: Ort
        name: ort
        widget: string
        hint: z.B. Aula Bürglen
      - label: Bilder
        name: bild
        required: false
        widget: "list"
        max: 10
        min: 0
        collapsed: false
        field:
          name: bild
          label_singular: Bild
          widget: image
          required: true
          allow_multiple: false
          choose_url: false
          media_library:
            config:
              max_file_size: 1048576 # 1MB
      - label: Inhalt
        name: body
        widget: markdown
        required: false
    sortable_fields: ["datum", "title"]
    view_groups:
      - label: Jahr
        field: datum
        pattern: \d{4}
